### PR TITLE
Primary key removed form update documents

### PR DESCRIPTION
**Pull request by sanders41**
Removed based on conversation here https://github.com/meilisearch/meilisearch-python/issues/224. Should consider re-adding based on new information

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @sanders41 ! 
I'm so sorry I really was confused yesterday. It is possible to use primary key with update documents as it also can be used to add documents and so, creating an index if non exists, as per the documentation: https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents

Nevertheless, It creates a weird to document explaination thus removing is not per se a bad think.

**Comment by sanders41** [comment]
No problem, I was confused myself! It does create a weird situation with the current setup because I checked and the server does return a failed status if a primary key is included. In addition as a user, based on the method name, I would expect the primary key to update.

Same with the add documents, I’m still not sure how to get that to work. I always seem to get the first column, or None for the primary key.

**Comment by bidoubiwa** [comment]
We are in process of rethinking some design choices on the MeiliSearch API. Could you, if you want to of course, create an issue on the meilisearch repository to point out this weird behavior? As user feedbacks will help us decide where to go with the design. 

I agree with you that it is really confusing!

**Comment by sanders41** [comment]
Done 😄 https://github.com/meilisearch/MeiliSearch/issues/1274

Thanks for your help on this.

**Comment by curquiza** [comment]
This is not related to a design choice of MeiliSearch but to a design choice of the SDK itself. See https://github.com/meilisearch/meilisearch-python/issues/224#issuecomment-793026949

Sorry if I miss understood something 😇

**Pull request merged**
